baseURL = 'https://www.noobsec.net/'
languageCode = 'en-us'
title = 'Welcome to noobsec'
theme = 'hugo-theme-monochrome'
enableEmoji = 'true'

[services]
  [services.disqus]
    shortname = 'n00bsec'
  [services.googleAnalytics]
    id = 'G-VZX99LLTQ8'

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[outputs]
home = ["HTML", "RSS", "JSON"]

[sitemap]
  changefreq = 'weekly'
  filename = 'sitemap.xml'
  priority = 0.5